INSERT INTO BOOK (ID, AUTHOR, DESCRIPTION, ISBN, TITLE, YEAR) VALUES (1, 'Author 1', 'Bla bla 1', '11111', 'Book 1 Title', 1049);
INSERT INTO BOOK (ID, AUTHOR, DESCRIPTION, ISBN, TITLE, YEAR) VALUES (2, 'Author 2', 'Bla bla 2', '11112', 'Book 2 Title', 1059);
INSERT INTO BOOK (ID, AUTHOR, DESCRIPTION, ISBN, TITLE, YEAR) VALUES (3, 'Author 3', 'Bla bla 3', '11113', 'Book 3 Title', 1069);
INSERT INTO BOOK (ID, AUTHOR, DESCRIPTION, ISBN, TITLE, YEAR) VALUES (4, 'Author 4', 'Bla bla 4', '11114', 'Book 4 Title', 1079);
